// Generated file - DO NOT EDIT MANUALLY
// This file is automatically generated by Spider's generateEmbeddedTemplates
// Source directory: src/

pub const EmbeddedTemplates = struct {

    home_index: []const u8 = @embedFile("views/home/index.html"),
    dashbord_index: []const u8 = @embedFile("views/dashbord/index.html"),
    bills_index: []const u8 = @embedFile("views/bills/index.html"),
    layout: []const u8 = @embedFile("layout.html"),
    Card: []const u8 = @embedFile("shared/templates/Card.html"),
    BillCard: []const u8 = @embedFile("shared/templates/BillCard.html"),
    dashboard: []const u8 = @embedFile("dashboard.html"),

};
