version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: pg-benchmark
    restart: unless-stopped
    environment:
      POSTGRES_USER: benchmark
      POSTGRES_PASSWORD: benchmark
      POSTGRES_DB: hello_world
    ports:
      - "5432:5432"
    command: >
      postgres
      -c max_connections=100
      -c shared_buffers=1GB
      -c effective_cache_size=3GB
      -c work_mem=4MB
      -c maintenance_work_mem=256MB
      -c synchronous_commit=off
      -c wal_level=minimal
      -c max_wal_senders=0
      -c max_wal_size=1GB
      -c checkpoint_timeout=15min
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
