const std = @import("std");

const GenerateTemplatesStep = @This();

step: std.Build.Step,
source_dir: []const u8,
output_path: []const u8,
b: *std.Build,

pub fn create(
    b: *std.Build,
    source_dir: []const u8,
    output_path: []const u8,
) *GenerateTemplatesStep {
    const self = b.allocator.create(GenerateTemplatesStep) catch @panic("out of memory");

    self.* = .{
        .step = std.Build.Step.init(.{
            .id = .custom,
            .name = "GenerateTemplates",
            .owner = b,
            .makeFn = make,
        }),
        .source_dir = b.dupe(source_dir),
        .output_path = b.dupe(output_path),
        .b = b,
    };

    return self;
}

fn make(step: *std.Build.Step, progress_node: *std.Progress.Node) anyerror!void {
    _ = progress_node;
    const self = @as(*GenerateTemplatesStep, @ptrCast(@alignCast(step)));

    var arena = std.heap.ArenaAllocator.init(std.heap.page_allocator);
    defer arena.deinit();
    const allocator = arena.allocator();

    var output = try std.ArrayList(u8).initCapacity(allocator, 4096);
    defer output.deinit();

    try output.appendSlice("// Generated file - DO NOT EDIT MANUALLY\n");
    try output.appendSlice("// This file is automatically generated by Spider's GenerateTemplatesStep\n");
    const source_dir_line = try std.fmt.allocPrint(allocator, "// Source directory: {s}\n\n", .{self.source_dir});
    defer allocator.free(source_dir_line);
    try output.appendSlice(source_dir_line);
    try output.appendSlice("pub const EmbeddedTemplates = struct {\n\n");

    const io = std.io;
    const cwd = std.fs.cwd();
    var dir = try cwd.openDir(self.source_dir, .{ .iterate = true });
    defer dir.close();

    var walker = try dir.walk(allocator);
    defer walker.deinit();

    var template_count: usize = 0;

    while (try walker.next(io)) |entry| {
        if (entry.kind != .file) continue;

        // Only process HTML files
        if (!std.mem.endsWith(u8, entry.path, ".html")) continue;

        // Generate field name from path
        var field_name_buf: [256]u8 = undefined;
        const field_name = try generateFieldName(entry.path, &field_name_buf);

        // Get relative path from source directory
        const full_path = try std.fs.path.join(allocator, &.{ self.source_dir, entry.path });

        const line = try std.fmt.allocPrint(allocator, "    {s}: []const u8 = @embedFile(\"{s}\"),\n", .{ field_name, full_path });
        defer allocator.free(line);
        try output.appendSlice(line);
        template_count += 1;
    }

    try output.appendSlice("\n};\n");

    // Write to file
    const out_file = try cwd.createFile(self.output_path, .{});
    defer out_file.close();

    try out_file.writeAll(output.items);

    std.log.info("Generated {d} embedded templates in {s}", .{ template_count, self.output_path });
}

fn generateFieldName(path: []const u8, buffer: []u8) ![]const u8 {
    var parts = std.mem.splitScalar(u8, path, std.fs.path.sep);
    var result = try std.ArrayList(u8).initCapacity(std.heap.page_allocator, 256);
    defer result.deinit();

    var first = true;
    while (parts.next()) |part| {
        if (std.mem.eql(u8, part, "views")) continue;
        if (std.mem.endsWith(u8, part, ".html")) {
            const base_name = part[0 .. part.len - 5]; // Remove .html
            if (!first) try result.appendSlice("_");
            try result.appendSlice(base_name);
        } else {
            if (!first) try result.appendSlice("_");
            try result.appendSlice(part);
        }
        first = false;
    }

    // Replace invalid characters
    for (result.items) |*char| {
        if (char.* == '-') char.* = '_';
        if (char.* == '.') char.* = '_';
    }

    return try std.fmt.bufPrint(buffer, "{s}", .{result.items});
}
