//! `spider check [--strict]`: the app's conventions (src/conventions.zig in
//! Spider) — routes in routes.zig with declared access, ui-* classes, icons
//! from active sets, features registered. Exit 1 on errors (and on warnings
//! with --strict). Apps generated by spider new run the same checks in
//! `zig build test` (spider.testing.expectConventions()).

const std = @import("std");
const conventions = @import("spider_testing").conventions;
const fs_utils = @import("fs_utils.zig");

pub fn run(io: std.Io, allocator: std.mem.Allocator, args: []const []const u8) !u8 {
    var strict = false;
    for (args) |a| {
        if (std.mem.eql(u8, a, "--strict")) {
            strict = true;
        } else {
            std.debug.print("error: unknown option '{s}' for `spider check` (see `spider check --help`)\n", .{a});
            return 2;
        }
    }
    const root = fs_utils.findProjectRoot(io) catch {
        std.debug.print("error: not inside a Spider app (no build.zig.zon here or above)\n", .{});
        return 2;
    };
    var arena = std.heap.ArenaAllocator.init(allocator);
    defer arena.deinit();
    var report: conventions.Report = .{ .arena = arena.allocator() };
    try conventions.check(io, arena.allocator(), root, &report);

    var buf: [4096]u8 = undefined;
    var w = std.Io.File.stdout().writer(io, &buf);
    if (report.issues.items.len == 0) {
        try w.interface.writeAll("ok: the app follows Spider's conventions\n");
    } else {
        try report.write(&w.interface);
    }
    try w.interface.flush();
    if (report.count(.err) > 0) return 1;
    if (strict and report.count(.warn) > 0) return 1;
    return 0;
}
