// Generated file - DO NOT EDIT MANUALLY
// This file is automatically generated by Spider's generateEmbeddedTemplates
// Source directory: src/

pub const EmbeddedTemplates = struct {

    view_index: []const u8 = @embedFile("view/index.html"),

};
