const std = @import("std");

pub fn main(init: std.process.Init) !void {
    const io = init.io;
    const allocator = init.arena.allocator();

    var args_it = std.process.Args.Iterator.init(init.minimal.args);
    _ = args_it.next(); // Skip program name

    const source_dir = args_it.next() orelse {
        std.debug.print("Usage: generate-templates <source_dir> <output_file>\n", .{});
        return error.InvalidArgs;
    };

    const output_file = args_it.next() orelse {
        std.debug.print("Usage: generate-templates <source_dir> <output_file>\n", .{});
        return error.InvalidArgs;
    };

    var output = try std.ArrayList(u8).initCapacity(allocator, 4096);
    defer output.deinit(allocator);

    try output.appendSlice(allocator, "// Generated file - DO NOT EDIT MANUALLY\n");
    try output.appendSlice(allocator, "// This file is automatically generated by Spider's generateEmbeddedTemplates\n");
    const source_dir_line = try std.fmt.allocPrint(allocator, "// Source directory: {s}\n\n", .{source_dir});
    defer allocator.free(source_dir_line);
    try output.appendSlice(allocator, source_dir_line);
    try output.appendSlice(allocator, "pub const EmbeddedTemplates = struct {\n\n");

    const cwd = std.Io.Dir.cwd();
    var dir = try cwd.openDir(io, source_dir, .{ .iterate = true });
    defer dir.close(io);

    var walker = try dir.walk(allocator);
    defer walker.deinit();

    var template_count: usize = 0;

    while (try walker.next(io)) |entry| {
        if (entry.kind != .file) continue;

        // Only process HTML files
        if (!std.mem.endsWith(u8, entry.path, ".html")) continue;

        // Generate field name from path
        var field_name_buf: [256]u8 = undefined;
        const field_name = try generateFieldName(entry.path, &field_name_buf);

        // Get relative path from source directory
        const full_path = try std.fs.path.join(allocator, &.{ source_dir, entry.path });

        const line = try std.fmt.allocPrint(allocator, "    {s}: []const u8 = @embedFile(\"{s}\"),\n", .{ field_name, full_path });
        defer allocator.free(line);
        try output.appendSlice(allocator, line);
        template_count += 1;
    }

    try output.appendSlice(allocator, "\n};\n");

    // Write to file
    const out_file = try cwd.createFile(io, output_file, .{});
    defer out_file.close(io);

    var buffer: [4096]u8 = undefined;
    var writer: std.Io.File.Writer = .init(out_file, io, &buffer);
    try writer.interface.writeAll(output.items);
    try writer.interface.flush();

    std.debug.print("Generated {d} embedded templates in {s}\n", .{ template_count, output_file });
}

fn generateFieldName(path: []const u8, buffer: []u8) ![]const u8 {
    var parts = std.mem.splitScalar(u8, path, std.fs.path.sep);
    var result = try std.ArrayList(u8).initCapacity(std.heap.page_allocator, 256);
    defer result.deinit(std.heap.page_allocator);

    var first = true;
    while (parts.next()) |part| {
        if (std.mem.eql(u8, part, "views")) continue;
        if (std.mem.endsWith(u8, part, ".html")) {
            const base_name = part[0 .. part.len - 5]; // Remove .html
            if (!first) try result.appendSlice(std.heap.page_allocator, "_");
            try result.appendSlice(std.heap.page_allocator, base_name);
        } else {
            if (!first) try result.appendSlice(std.heap.page_allocator, "_");
            try result.appendSlice(std.heap.page_allocator, part);
        }
        first = false;
    }

    // Replace invalid characters
    for (result.items) |*char| {
        if (char.* == '-') char.* = '_';
        if (char.* == '.') char.* = '_';
    }

    return try std.fmt.bufPrint(buffer, "{s}", .{result.items});
}
