const std = @import("std");

pub fn main(init: std.process.Init) !void {
    const io = init.io;
    const allocator = init.arena.allocator();

    var args_it = std.process.Args.Iterator.init(init.minimal.args);
    _ = args_it.next(); // Skip program name

    const source_dir = args_it.next() orelse {
        std.debug.print("Usage: generate-templates <source_dir> <output_file>\n", .{});
        return error.InvalidArgs;
    };

    const output_file = args_it.next() orelse {
        std.debug.print("Usage: generate-templates <source_dir> <output_file>\n", .{});
        return error.InvalidArgs;
    };

    var output = try std.ArrayList(u8).initCapacity(allocator, 4096);
    defer output.deinit(allocator);

    try output.appendSlice(allocator, "// Generated file - DO NOT EDIT MANUALLY\n");
    try output.appendSlice(allocator, "// This file is automatically generated by Spider's generateEmbeddedTemplates\n");
    const source_dir_line = try std.fmt.allocPrint(allocator, "// Source directory: {s}\n\n", .{source_dir});
    defer allocator.free(source_dir_line);
    try output.appendSlice(allocator, source_dir_line);
    try output.appendSlice(allocator, "pub const EmbeddedTemplates = struct {\n\n");

    const cwd = std.Io.Dir.cwd();
    var dir = try cwd.openDir(io, source_dir, .{ .iterate = true });
    defer dir.close(io);

    var walker = try dir.walk(allocator);
    defer walker.deinit();

    var template_count: usize = 0;

    while (try walker.next(io)) |entry| {
        if (entry.kind != .file) continue;

        // Only process HTML files
        if (!std.mem.endsWith(u8, entry.path, ".html")) continue;

        // Generate field name from path
        var field_name_buf: [256]u8 = undefined;
        const field_name = try generateFieldName(entry.path, &field_name_buf);

        // Use relative path for @embedFile (relative to the generated file location)
        const embed_path = entry.path;

        const line = try std.fmt.allocPrint(allocator, "    {s}: []const u8 = @embedFile(\"{s}\"),\n", .{ field_name, embed_path });
        defer allocator.free(line);
        try output.appendSlice(allocator, line);
        template_count += 1;
    }

    try output.appendSlice(allocator, "\n};\n");

    // Write to file
    const out_file = try cwd.createFile(io, output_file, .{});
    defer out_file.close(io);

    var buffer: [4096]u8 = undefined;
    var writer: std.Io.File.Writer = .init(out_file, io, &buffer);
    try writer.interface.writeAll(output.items);
    try writer.interface.flush();

    std.debug.print("Ride the lightning — {d} templates forged in {s}\n", .{ template_count, output_file });
}

fn generateFieldName(path: []const u8, buffer: []u8) ![]const u8 {
    // Remove .html extension
    const name_without_html = if (std.mem.endsWith(u8, path, ".html"))
        path[0 .. path.len - 5]
    else
        path;

    // Rule 1: If path contains "views/"
    if (std.mem.indexOf(u8, name_without_html, "views/") != null) {
        const views_pos = std.mem.indexOf(u8, name_without_html, "views/").?;

        // Find the "/" that precedes "views/" - look backwards from views_pos
        var search_end = views_pos;
        if (search_end > 0 and name_without_html[search_end - 1] == '/') {
            search_end -= 1;
        }

        // Find the "/" that precedes "views/" (the "/" between the dir and "views")
        // For "features/auth/views", this is the "/" at position 15
        const slash_before_views = std.mem.lastIndexOf(u8, name_without_html[0..views_pos], "/");

        // Now find the "/" before THAT - that's the real directory component
        const dir_start: usize = if (slash_before_views) |sbv_pos|
            (std.mem.lastIndexOf(u8, name_without_html[0..sbv_pos], "/") orelse 0) + 1
        else
            0;

        const dir_part = name_without_html[dir_start..slash_before_views.?];

        // Get the filename after "views/"
        const after_views = name_without_html[views_pos + 6 ..];

        // Build result: dir_part _ filename
        var result: [256]u8 = undefined;
        var j: usize = 0;
        for (dir_part) |char| {
            if (char == '-') {
                result[j] = '_';
                j += 1;
            } else {
                result[j] = char;
                j += 1;
            }
        }
        result[j] = '_';
        j += 1;
        for (after_views) |char| {
            if (char == '-') {
                result[j] = '_';
                j += 1;
            } else {
                result[j] = char;
                j += 1;
            }
        }

        return try std.fmt.bufPrint(buffer, "{s}", .{result[0..j]});
    }

    // Rule 2: No "views/" - remove generic prefixes
    var remaining = name_without_html;

    if (std.mem.startsWith(u8, remaining, "features/")) {
        remaining = remaining["features/".len..];
    } else if (std.mem.startsWith(u8, remaining, "shared/templates/")) {
        remaining = remaining["shared/templates/".len..];
    }

    // Replace / with _ and - with _
    var result: [256]u8 = undefined;
    var j: usize = 0;
    for (remaining) |char| {
        if (char == '/') {
            result[j] = '_';
            j += 1;
        } else if (char == '-') {
            result[j] = '_';
            j += 1;
        } else {
            result[j] = char;
            j += 1;
        }
    }

    return try std.fmt.bufPrint(buffer, "{s}", .{result[0..j]});
}
