//! Build-time tool behind `testManifest()` in build.zig: scans a module's
//! directory for files that declare `test "..."` blocks and writes the Zig
//! source of the manifest module read by
//! `spider.testing.expectAllTestsDiscovered`.
//!
//! It runs on every build (a Run step with side effects): a scan done while
//! build.zig is configured goes stale, because Zig caches that phase until
//! build.zig itself changes — a new test file would never be noticed.
//!
//! Usage: spider-test-manifest <dir> <out.zig> <display_dir> [exclude...]

const std = @import("std");
const testing = @import("testing.zig");

pub fn main(init: std.process.Init) !void {
    const io = init.io;
    const alc = init.arena.allocator();

    var args: std.ArrayList([]const u8) = .empty;
    {
        var it = try std.process.Args.Iterator.initAllocator(init.minimal.args, alc);
        defer it.deinit();
        _ = it.next();
        while (it.next()) |a| try args.append(alc, try alc.dupe(u8, a));
    }
    if (args.items.len < 3) {
        std.debug.print("usage: spider-test-manifest <dir> <out.zig> <display_dir> [exclude...]\n", .{});
        std.process.exit(2);
    }
    const dir_path = args.items[0];
    const out_path = args.items[1];
    const display_dir = args.items[2];
    const exclude = args.items[3..];

    var paths: std.ArrayList([]const u8) = .empty;
    var root = try std.Io.Dir.cwd().openDir(io, dir_path, .{ .iterate = true });
    defer root.close(io);
    var walker = try root.walk(alc);
    defer walker.deinit();
    walk: while (try walker.next(io)) |entry| {
        if (entry.kind != .file or !std.mem.endsWith(u8, entry.path, ".zig")) continue;
        for (exclude) |e| if (std.mem.startsWith(u8, entry.path, e)) continue :walk;
        const source = root.readFileAlloc(io, entry.path, alc, .limited(16 * 1024 * 1024)) catch continue;
        if (!testing.declaresTests(source)) continue;
        try paths.append(alc, try alc.dupe(u8, entry.path));
    }
    std.mem.sort([]const u8, paths.items, {}, struct {
        fn lt(_: void, a: []const u8, b: []const u8) bool {
            return std.mem.lessThan(u8, a, b);
        }
    }.lt);

    var out: std.ArrayList(u8) = .empty;
    try out.appendSlice(alc, "// Generated by spider-test-manifest. Do not edit.\npub const paths: []const []const u8 = &.{\n");
    for (paths.items) |p| try out.print(alc, "    \"{f}\",\n", .{std.zig.fmtString(try std.fs.path.join(alc, &.{ display_dir, p }))});
    try out.appendSlice(alc, "};\npub const prefixes: []const []const u8 = &.{\n");
    var buf: [1024]u8 = undefined;
    for (paths.items) |p| try out.print(alc, "    \"{f}\",\n", .{std.zig.fmtString(testing.prefixFor(&buf, p))});
    try out.appendSlice(alc, "};\n");

    const file = try std.Io.Dir.cwd().createFile(io, out_path, .{});
    defer file.close(io);
    var wbuf: [4096]u8 = undefined;
    var w = file.writer(io, &wbuf);
    try w.interface.writeAll(out.items);
    try w.interface.flush();
}
