//! Test helpers for apps (`spider.testing`): requests against the running
//! app (`start`), a feature's access table (`expectRoutes`), the app's
//! conventions (`expectConventions`), and the check that catches test files
//! `zig build test` silently skips (`expectAllTestsDiscovered`).
//!
//! Zig only compiles the `test` blocks of files it analyzes as a whole from
//! the test binary's root module (the root file, and files imported from a
//! `test {}` block or through `std.testing.refAllDecls`, which goes one
//! level deep). A file with tests that isn't reached that way is skipped
//! without a word, and the step still reports success.
//!
//! Usage (see `testManifest` in Spider's build.zig):
//!
//! ```zig
//! // build.zig
//! const spider_build = @import("spider");
//! features_mod.addImport("test_manifest", spider_build.testManifest(b, "src/features"));
//!
//! // src/features/mod.zig (the module's root file)
//! test "every test file is part of this test binary" {
//!     try spider.testing.expectAllTestsDiscovered(@import("test_manifest"));
//! }
//! ```

const std = @import("std");
const builtin = @import("builtin");

/// The app conventions behind expectConventions() and `spider check`.
pub const conventions = @import("conventions.zig");

/// Requests against the running app, in a test: see testing/http.zig.
///
/// ```zig
/// const app = try spider.testing.start(run);
/// var res = try app.get("/posts");
/// defer res.deinit();
/// try res.expectStatus(200);
/// ```
pub const http = @import("testing/http.zig");
/// Starts the app once for the test binary and gives back where to send requests.
pub const start = http.start;
/// The server started by `start`: `get`, `postForm`, `postJson`, `request`,
/// and `with` for headers sent with every request.
pub const App = http.App;
/// What the server answered, with `expectStatus`, `expectContains` and the like.
pub const Response = http.Response;

/// A feature's access contract: see routing/expect_routes.zig.
pub const expectRoutes = @import("routing/expect_routes.zig").expectRoutes;

/// The app follows Spider's conventions (conventions.zig): fails with
/// `error.ConventionsViolated`, listing each problem with its file, line
/// and fix — the same report as `spider check`. Warnings alone do not
/// fail it. Generated apps call it from a test in src/main.zig. Finds the
/// project root by walking up from the working directory to
/// build.zig.zon (`error.ProjectRootNotFound` when none is found 20
/// levels up). For tests only: it uses `std.testing`.
pub fn expectConventions() !void {
    const io = std.testing.io;
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    var root = std.Io.Dir.cwd();
    var depth: usize = 0;
    while (true) : (depth += 1) {
        if (root.access(io, "build.zig.zon", .{})) |_| break else |_| {}
        if (depth == 20) return error.ProjectRootNotFound;
        root = try root.openDir(io, "..", .{});
    }
    var report: conventions.Report = .{ .arena = arena.allocator() };
    try conventions.check(io, arena.allocator(), root, &report);
    if (report.count(.err) == 0) return;
    var buf: [4096]u8 = undefined;
    var w = std.Io.File.stderr().writer(io, &buf);
    w.interface.writeAll("\nSpider conventions (`spider check` shows the same):\n") catch {};
    report.write(&w.interface) catch {};
    w.interface.flush() catch {};
    return error.ConventionsViolated;
}

/// `manifest` is the module generated by `testManifest()`: parallel lists of
/// the files under the module's root directory that declare `test "..."`
/// blocks (`paths`) and the name prefix Zig gives their tests (`prefixes`).
/// Fails with `error.TestFilesNotDiscovered`, naming each file, when one of
/// them has no test in this binary.
pub fn expectAllTestsDiscovered(comptime manifest: type) !void {
    var missing: usize = 0;
    for (manifest.prefixes, manifest.paths) |prefix, path| {
        if (binaryHasTestWithPrefix(prefix)) continue;
        if (missing == 0) std.debug.print("\n", .{});
        missing += 1;
        std.debug.print(
            "test file not part of this test binary (its tests never run): {s}\n" ++
                "  fix: import it from a `test {{}}` block of a file that is, e.g.\n" ++
                "       `test {{ _ = @import(\"{s}\"); }}` in the mod.zig next to it,\n" ++
                "       or `test {{ @import(\"std\").testing.refAllDecls(@This()); }}` there\n",
            .{ path, std.fs.path.basename(path) },
        );
    }
    if (missing > 0) return error.TestFilesNotDiscovered;
}

fn binaryHasTestWithPrefix(prefix: []const u8) bool {
    for (builtin.test_functions) |t| {
        if (isTestOf(t.name, prefix)) return true;
    }
    return false;
}

/// "posts.model.test.y" / "posts.model.test_0" belong to "posts.model".
fn isTestOf(name: []const u8, prefix: []const u8) bool {
    if (name.len <= prefix.len or !std.mem.startsWith(u8, name, prefix)) return false;
    const rest = name[prefix.len..];
    return std.mem.startsWith(u8, rest, ".test.") or std.mem.startsWith(u8, rest, ".test_");
}

/// Test-name prefix Zig uses for a file at `rel_path` (relative to the
/// module's root directory): "posts/model.zig" -> "posts.model". Written
/// into `buf`, and cut to its length.
pub fn prefixFor(buf: []u8, rel_path: []const u8) []const u8 {
    const stem = if (std.mem.endsWith(u8, rel_path, ".zig")) rel_path[0 .. rel_path.len - 4] else rel_path;
    const n = @min(stem.len, buf.len);
    for (stem[0..n], 0..) |ch, i| buf[i] = if (ch == '/' or ch == '\\') '.' else ch;
    return buf[0..n];
}

/// Whether Zig source text declares a named test (`test "..."` at the start
/// of a line).
pub fn declaresTests(source: []const u8) bool {
    if (std.mem.startsWith(u8, source, "test \"")) return true;
    return std.mem.indexOf(u8, source, "\ntest \"") != null;
}

test "prefixFor" {
    var buf: [128]u8 = undefined;
    try std.testing.expectEqualStrings("posts.model", prefixFor(&buf, "posts/model.zig"));
    try std.testing.expectEqualStrings("mod", prefixFor(&buf, "mod.zig"));
}

test "declaresTests" {
    try std.testing.expect(declaresTests("test \"a\" {}"));
    try std.testing.expect(declaresTests("const x = 1;\ntest \"a\" {}"));
    try std.testing.expect(!declaresTests("test {\n    _ = x;\n}"));
    try std.testing.expect(!declaresTests("// test \"a\""));
}

test "isTestOf" {
    try std.testing.expect(isTestOf("posts.model.test.y", "posts.model"));
    try std.testing.expect(isTestOf("posts.mod.test_0", "posts.mod"));
    try std.testing.expect(!isTestOf("posts.model.test.y", "posts"));
    try std.testing.expect(!isTestOf("posts.model.test.y", "posts.mode"));
    try std.testing.expect(!isTestOf("mod.test.x", "posts.controller"));
}
